//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public int InspeccionId { get; set; }
        public Nullable<int> VehiculoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public Nullable<int> CantidadCombustibleId { get; set; }
        public Nullable<bool> TieneRalladuras { get; set; }
        public Nullable<bool> TieneGomaRespuesta { get; set; }
        public Nullable<bool> TieneGato { get; set; }
        public Nullable<bool> TieneRoturasCristal { get; set; }
        public Nullable<bool> GomaDelanteraIzquierda { get; set; }
        public Nullable<bool> GomaDelanteraDerecha { get; set; }
        public Nullable<bool> GomaTraceraIzquierda { get; set; }
        public Nullable<bool> GomaTraceraDerecha { get; set; }
        public string Etc { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual CantidadCombustible CantidadCombustible { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
