//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentCarDBEntities : DbContext
    {
        public RentCarDBEntities()
            : base("name=RentCarDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CantidadCombustible> CantidadCombustible { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Inspeccion> Inspeccion { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<TandaLaboral> TandaLaboral { get; set; }
        public virtual DbSet<TipoCombustible> TipoCombustible { get; set; }
        public virtual DbSet<TipoPersona> TipoPersona { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculo { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
        public virtual DbSet<View_CantidadCombustible> View_CantidadCombustible { get; set; }
        public virtual DbSet<View_Cliente> View_Cliente { get; set; }
        public virtual DbSet<View_Empleado> View_Empleado { get; set; }
        public virtual DbSet<View_Inspeccion> View_Inspeccion { get; set; }
        public virtual DbSet<View_Marca> View_Marca { get; set; }
        public virtual DbSet<View_Modelo> View_Modelo { get; set; }
        public virtual DbSet<View_TandaLaboral> View_TandaLaboral { get; set; }
        public virtual DbSet<View_TipoCombustible> View_TipoCombustible { get; set; }
        public virtual DbSet<View_TipoPersona> View_TipoPersona { get; set; }
        public virtual DbSet<View_TipoVehiculo> View_TipoVehiculo { get; set; }
        public virtual DbSet<View_Vehiculo> View_Vehiculo { get; set; }
        public virtual DbSet<Renta> Renta { get; set; }
        public virtual DbSet<View_Renta> View_Renta { get; set; }
        public virtual DbSet<View_Rentas> View_Rentas { get; set; }
    }
}
