//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renta
    {
        public int RentaId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public Nullable<int> VehiculoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<System.DateTime> FechaRenta { get; set; }
        public Nullable<System.DateTime> FechaEsperada { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public Nullable<decimal> MontoDiario { get; set; }
        public Nullable<int> Dias { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
