//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Vehiculo
    {
        public int VehiculoId { get; set; }
        public Nullable<int> TipoVehiculoId { get; set; }
        public Nullable<int> MarcaId { get; set; }
        public Nullable<int> ModeloId { get; set; }
        public Nullable<int> TipoCombustibleId { get; set; }
        public string Descripcion { get; set; }
        public string Chasis { get; set; }
        public string Motor { get; set; }
        public string Placa { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
