//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Empleado
    {
        public int EmpleadoId { get; set; }
        public Nullable<int> TandaLaboralId { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public Nullable<int> PorcientoComision { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
